name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Newman
        run: npm install -g newman

      - name: Create Docker Network
        run: docker network create test_network

      - name: Build unit test images
        run: |
          docker build -t test_calc -f src/calc/Dockerfile_test src/calc
          docker build -t test_string -f src/string/Dockerfile_test src/string
          docker build -t test_gateway -f src/gateway/Dockerfile src/gateway

      - name: Run unit test containers
        run: |
          docker run -d --name calc_test_container --network test_network test_calc
          docker run -d --name string_test_container --network test_network test_string
          docker run -d --name gateway_test_container --network test_network -p 5000:5000 test_gateway
          sleep 5  # Aspetta che i servizi siano avviati

      - name: Run unit tests with Newman (Gateway as API entry point)
        run: |
          newman run tests/calc_ut.postman_collection.json
          newman run tests/string_ut.postman_collection.json

      - name: Stop unit test containers
        run: |
          docker stop calc_test_container string_test_container gateway_test_container
          docker rm calc_test_container string_test_container gateway_test_container

      - name: Remove Docker Network
        run: docker network rm test_network

  integration-tests:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: docker-compose -f src/docker-compose.yml up --build -d

      - name: Wait for services to start
        run: sleep 10  # Aspetta che tutti i servizi siano attivi

      - name: Run integration tests with Newman
        run: newman run tests/integration.postman_collection.json

      - name: Teardown Docker Compose
        run: docker-compose -f src/docker-compose.yml down
