name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Newman
        run: npm install -g newman

      - name: Build unit test images
        run: |
          docker build -t test_calc -f calc/Dockerfile_test .
          docker build -t test_string -f string/Dockerfile_test .

      - name: Run unit test containers
        run: |
          docker run -d --name calc_test_container test_calc
          docker run -d --name string_test_container test_string

      - name: Run unit tests with Newman
        run: |
          newman run tests/calc.postman_collection.json
          newman run tests/string.postman_collection.json

      - name: Stop unit test containers
        run: |
          docker stop calc_test_container string_test_container
          docker rm calc_test_container string_test_container

  integration-tests:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: docker-compose up --build -d

      - name: Run integration tests with Newman
        run: newman run tests/gateway.postman_collection.json

      - name: Teardown Docker Compose
        run: docker-compose down
